[workspace]
members = [
    "core",
    "cli",
    "extensions", "markhor",
    "gui", 
    "markhor", 
    "util", 
]
resolver = "3" # Use the edition 2024 resolver

[workspace.package]
version = "0.1.0-alpha.0.2"
